import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "../providers";
import localFont from "next/font/local";

const iBrand = localFont({
  src: "../public/fonts/ibrand.otf",
  variable: "--font-ibrand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={iBrand.variable}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
