import { FaqAccordionItem, SiteInternationaux } from "@/types/index.type";
import { CarRentalOption } from "@/types/location-voiture.type";
import { Destination, LocationValue } from "@/types/vols.type";
import { Users, Contact, Plane, BedDouble, Car, Flag, Globe, HelpCircle } from "lucide-react";

export const menuItems = {
    desktop: [
      {
        name: "A propos de Fastosh",
        path: "/apropos-de",
        icone: Users,
      },
      {
        name: "Contactez-nous",
        path: "/contact",
        icone: Contact,
      },
    ],
    mobile: [
      { name: "Vols", path: "/vols", icone: Plane },
      {
        name: "Hôtels",
        path: "/hotels",
        icone: BedDouble,
      },
      {
        name: "Location de voiture",
        path: "/location-de-voiture",
        icone: Car,
      },
    ],
    other: [
      {
        name: "Paramètres régionaux",
        path: "/parametres-regionaux",
        icone: Flag,
      },
      {
        name: "Explorez le monde entier",
        path: "/explorer",
        icone: Globe,
      },
      { name: "Aide", path: "/aide", icone: HelpCircle },
    ],
  };

export const faqs: FaqAccordionItem[] = [
    {
        id: 1,
        title: "Comment fonctionne Fastosh ?",
        content: "Fastosh est un moteur de recherche de vols, de voitures de location et d'hôtels. Nous parcourons le Web pour trouver les meilleurs prestataires de voyage et compagnies aériennes, afin que vous puissiez comparer les tarifs des vols et les autres prix au même endroit. Une fois que vous avez trouvé votre vol, votre voiture de location ou votre hôtel, il suffit de réserver directement auprès du prestataire.",
    },
    {
        id: 2,
        title: "Comment trouver le vol le moins cher avec Fastosh ?",
        content: "Pour trouver des vols, c'est facile : chaque mois, plus de 100 millions de voyageurs avisés viennent sur notre site pour trouver des billets d'avion, des hôtels et des voitures de location pas chers. Voici quelques conseils simples pour tirer le meilleur parti de votre recherche de vol.\n\n" +
            "<strong>Gagnez du temps et de l'argent.</strong> Qu'il s'agisse du vol le plus rapide ou du séjour le plus avantageux, vous pouvez choisir votre compagnie aérienne ou votre hôtel préférés en fonction des notes réelles des voyageurs et réserver instantanément.\n\n" +
            "<strong>Cherchez dans le monde entier. Partez où vous voulez.</strong> Vous avez envie de voyager peu importe la destination ? Vous voulez découvrir un nouvel endroit ? Cherchez dans « <b>le monde entier</b> » pour trouver le vol le moins cher vers n'importe quelle destination le jour de votre choix.\n\n" +
            "<strong>Trouvez les périodes les moins chères pour prendre un vol.</strong> Si vous avez une destination en tête et que vous voulez trouver le vol le moins cher, sélectionnez « <b>Mois le moins cher</b> » lors de votre recherche. Vous trouverez alors des vols le jour où ils sont les moins chers.",
    },
    {
        id: 3,
        title: "Vers quelles destinations puis-je actuellement réserver un vol ?",
        content: "Si vous êtes à la recherche d'inspiration pour votre prochain voyage, utilisez notre fonctionnalité de <a href=\"transport/flights-from/CI\">recherche dans le monde entier</a> pour trouver un vol pas cher vers n'importe quelle destination.",
    },
    {
        id: 4,
        title: "Puis-je réserver mon vol avec Fastosh ?",
        content: "Fastosh étant un moteur de recherche, une fois que vous avez trouvé votre billet d'avion, vous devez le réserver directement sur le site de la compagnie aérienne ou du prestataire de voyage. Vous avez ainsi la possibilité d'ajouter les informations nécessaires au programme de fidélité et de choisir les options de vol que vous préférez, telles que l'emplacement du siège.",
    },
    {
        id: 5,
        title: "Que se passe-t-il une fois que j'ai réservé mon vol ?",
        content: "Votre e-mail de confirmation de réservation de vol et toutes les autres informations dont vous aurez besoin proviendront de la compagnie aérienne ou du prestataire avec qui vous avez réservé. Si vous avez des questions concernant le suivi de votre réservation, ou si vous souhaitez modifier ou annuler votre vol, adressez-vous à eux.",
    },

    {
        id: 6,
        title: "Peut-on rechercher aussi des hôtels sur Fastosh ?",
        content: "Oui ! Vous pouvez utiliser la puissance de notre moteur de recherche de vols pour trouver l'hébergement idéal n'importe où.",
    },
    {
        id: 7,
        title: "Et louer une voiture ?",
        content: "Vous pouvez également utiliser Fastosh pour rechercher et comparer des locations de véhicule pas chères en quelques secondes, puis récupérer votre voiture dès votre arrivée à l'aéroport.",
    },
    {
        id: 8,
        title: "Qu'est-ce qu'une alerte prix ?",
        content: "Si vous créez une alerte de prix, nous surveillerons les tarifs des billets d'avion pour vous et vous informerons par e-mail ou par notification push via l'application de toute nouvelle hausse ou baisse de prix.",
    },
    {
        id: 9,
        title: "Puis-je réserver un billet d'avion flexible ?",
        content: "Nous comprenons à quel point il est important d'avoir de la flexibilité pour les vacances. Comme il y a parfois des frais supplémentaires à régler pour avoir un billet d'avion modifiable, recherchez cette option lorsque vous effectuez votre réservation. Recherchez des hôtels et des options de location de voiture avec annulation gratuite afin de pouvoir réserver maintenant et modifier voire annuler plus tard si besoin.",
    },
    {
        id: 10,
        title: "Puis-je réserver des vols émettant moins de CO₂ ?",
        content: "Oui. Depuis que nous avons commencé à afficher les émissions de CO₂ des vols (quand cette information est disponible), plus de 100 millions de voyageurs ont trouvé un billet d'avion émettant moins de CO₂ pour leur trajet.",
    }
];

export const siteInternationaux: SiteInternationaux[] = [
    {
        country: "Royaume-Uni",
        code: "GB",
        url: "#",
        locale: "en-GB",
        market: "UK",
        labelText: "(GB) Cheap flights",
        image_url: "https://js.skyscnr.com/images/country/flag/header/uk.png",
    },
    {
        country: "Australie",
        code: "AU",
        url: "#",
        locale: "en-GB",
        market: "AU",
        labelText: "(AU) Australia - Cheap flights",
        image_url: "https://js.skyscnr.com/images/country/flag/header/au.png",
    },
    {
        country: "Chine",
        code: "CN",
        url: "#",
        locale: "zh-CN",
        market: "CN",
        labelText: "(CN) 中国 - 机票",
        image_url: "https://js.skyscnr.com/images/country/flag/header/cn.png",
    },
    {
        country: "Danemark",
        code: "DK",
        url: "#",
        locale: "da-DK",
        market: "DK",
        labelText: "(DK) Flybilletter",
        image_url: "https://js.skyscnr.com/images/country/flag/header/dk.png",
    },
    {
        country: "Finlande",
        code: "FI",
        url: "#",
        locale: "fi-FI",
        market: "FI",
        labelText: "(FI) Suomi - lennot",
        image_url: "https://js.skyscnr.com/images/country/flag/header/fi.png",
    },
    {
        country: "France",
        code: "FR",
        url: "#",
        locale: "fr-FR",
        market: "FR",
        labelText: "(FR) France - vols",
        image_url: "https://js.skyscnr.com/images/country/flag/header/fr.png",
    },
    {
        country: "Allemagne",
        code: "DE",
        url: "#",
        locale: "de-DE",
        market: "DE",
        labelText: "(DE) Deutschland - Flüge",
        image_url: "https://js.skyscnr.com/images/country/flag/header/de.png",
    },
    {
        country: "Inde",
        code: "IN",
        url: "#",
        locale: "en-GB",
        market: "IN",
        labelText: "(IN) India - Flight tickets",
        image_url: "https://js.skyscnr.com/images/country/flag/header/in.png",
    },
    {
        country: "Irlande",
        code: "IE",
        url: "#",
        locale: "en-GB",
        market: "IE",
        labelText: "(IE) Ireland - flights",
        image_url: "https://js.skyscnr.com/images/country/flag/header/ie.png",
    },
    {
        country: "Italie",
        code: "IT",
        url: "#",
        locale: "it-IT",
        market: "IT",
        labelText: "(IT) Italia - voli",
        image_url: "https://js.skyscnr.com/images/country/flag/header/it.png",
    },
    {
        country: "Japon",
        code: "JP",
        url: "#",
        locale: "ja-JP",
        market: "JP",
        labelText: "(JP) 日本 - 航空券",
        image_url: "https://js.skyscnr.com/images/country/flag/header/jp.png",
    },
    {
        country: "Mexique",
        code: "MX",
        url: "#",
        locale: "es-MX",
        market: "MX",
        labelText: "(MX) México - vuelos",
        image_url: "https://js.skyscnr.com/images/country/flag/header/mx.png",
    },
    {
        country: "Pays-Bas",
        code: "NL",
        url: "#",
        locale: "nl-NL",
        market: "NL",
        labelText: "(NL) Vliegtickets",
        image_url: "https://js.skyscnr.com/images/country/flag/header/nl.png",
    },
    {
        country: "Norvège",
        code: "NO",
        url: "#",
        locale: "nb-NO",
        market: "NO",
        labelText: "(NO) Billige flybilletter",
        image_url: "https://js.skyscnr.com/images/country/flag/header/no.png",
    },
    {
        country: "Pologne",
        code: "PL",
        url: "#",
        locale: "pl-PL",
        market: "PL",
        labelText: "(PL) Polska – tanie loty",
        image_url: "https://js.skyscnr.com/images/country/flag/header/pl.png",
    },
    {
        country: "Russie",
        code: "RU",
        url: "#",
        locale: "ru-RU",
        market: "RU",
        labelText: "(RU) Россия - авиабилеты",
        image_url: "https://js.skyscnr.com/images/country/flag/header/ru.png",

    },
    {
        country: "Espagne",
        code: "ES",
        url: "#",
        locale: "es-ES",
        market: "ES",
        labelText: "(ES) España - vuelos",
        image_url: "https://js.skyscnr.com/images/country/flag/header/es.png",
    },
    {
        country: "Suède",
        code: "SE",
        url: "#",
        locale: "sv-SE",
        market: "SE",
        labelText: "(SE) Sverige - flyg",
        image_url: "https://js.skyscnr.com/images/country/flag/header/se.png",
    },
    {
        country: "Suisse",
        code: "CH",
        url: "#",
        locale: "de-DE",
        market: "CH",
        labelText: "(CH) Schweiz - Flüge",
        image_url: "https://js.skyscnr.com/images/country/flag/header/ch.png",
    },
    {
        country: "Turquie",
        code: "TR",
        url: "#",
        locale: "tr-TR",
        market: "TR",
        labelText: "(TR) Türkiye - uçak biletleri",
        image_url: "https://js.skyscnr.com/images/country/flag/header/tr.png",
    },
    {
        country: "Emirats arabes",
        code: "AE",
        url: "#",
        locale: "en-US",
        market: "AE",
        labelText: "(AE) United Arab Emirates - flights",
        image_url: "https://js.skyscnr.com/images/country/flag/header/ae.png",
    },
    {
        country: "Etats-Unis",
        code: "US",
        url: "#",
        locale: "en-US",
        market: "US",
        labelText: "(US) USA - flights",
        image_url: "https://js.skyscnr.com/images/country/flag/header/us.png",
    }
];

export const destinations: Destination[] = [
    {
        id: 1,
        city: "San-Pédro",
        country: "Côte d'Ivoire",
        imageUrl: "/images/background/bg_1.jpg",
        flightOptions: [
            {
                dayOfWeek: "mer",
                date: "28 mai",
                departureAirport: "ABJ",
                arrivalAirport: "SPY",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
            {
                dayOfWeek: "jeu",
                date: "6 juin",
                departureAirport: "SPY",
                arrivalAirport: "ABJ",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
        ],
        startingPrice: "64.277F",
    },
    {
        id: 2,
        city: "Bamako",
        country: "Mali",
        imageUrl: "/images/background/bg_2.jpg",
        flightOptions: [
            {
                dayOfWeek: "jeu",
                date: "3 juil.",
                departureAirport: "ABJ",
                arrivalAirport: "BKO",
                airline: "Mauritania Airlines",
                isDirect: true,
            },
            {
                dayOfWeek: "jeu",
                date: "10 juil.",
                departureAirport: "BKO",
                arrivalAirport: "ABJ",
                airline: "Mauritania Airlines",
                isDirect: true,
            },
        ],
        startingPrice: "177.756F",
    },
    {
        id: 3,
        city: "Lomé",
        country: "Togo",
        imageUrl: "/images/background/bg_3.jpg",
        flightOptions: [
            {
                dayOfWeek: "mer",
                date: "11 juin",
                departureAirport: "ABJ",
                arrivalAirport: "LFW",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
            {
                dayOfWeek: "mar",
                date: "17 juin",
                departureAirport: "LFW",
                arrivalAirport: "ABJ",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
        ],
        startingPrice: "210.556F",
    },
    {
        id: 4,
        city: "Accra",
        country: "Ghana",
        imageUrl: "/images/background/bg_4.jpg",
        flightOptions: [
            {
                dayOfWeek: "ven",
                date: "19 juil.",
                departureAirport: "ABJ",
                arrivalAirport: "ACC",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
            {
                dayOfWeek: "sam",
                date: "26 juil.",
                departureAirport: "ACC",
                arrivalAirport: "ABJ",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
        ],
        startingPrice: "231.546F",
    },
    {
        id: 5,
        city: "Dakar",
        country: "Sénégal",
        imageUrl: "/images/background/bg_5.jpg",
        flightOptions: [
            {
                dayOfWeek: "sam",
                date: "5 juil.",
                departureAirport: "ABJ",
                arrivalAirport: "DSS",
                airline: "Mauritania Airlines",
                isDirect: true,
            },
            {
                dayOfWeek: "lun",
                date: "21 juil.",
                departureAirport: "DSS",
                arrivalAirport: "ABJ",
                airline: "Mauritania Airlines",
                isDirect: true,
            },
        ],
        startingPrice: "237.460F",
    },
    {
        id: 6,
        city: "Alger",
        country: "Algérie",
        imageUrl: "/images/background/bg_6.jpg",
        flightOptions: [
            {
                dayOfWeek: "jeu",
                date: "31 juil.",
                departureAirport: "ABJ",
                arrivalAirport: "ALG",
                airline: "Air Algérie",
                isDirect: true,
            },
            {
                dayOfWeek: "ven",
                date: "8 août",
                departureAirport: "ALG",
                arrivalAirport: "ABJ",
                airline: "Air Algérie",
                isDirect: true,
            },
        ],
        startingPrice: "252.537F",
    },
    {
        id: 7,
        city: "Conakry",
        country: "Guinée",
        imageUrl: "/images/background/bg_1.jpg",
        flightOptions: [
            {
                dayOfWeek: "jeu",
                date: "22 mai",
                departureAirport: "ABJ",
                arrivalAirport: "CKY",
                airline: "Air Sénégal",
                isDirect: true,
            },
            {
                dayOfWeek: "jeu",
                date: "29 mai",
                departureAirport: "CKY",
                arrivalAirport: "ABJ",
                airline: "Air Sénégal",
                isDirect: true,
            },
        ],
        startingPrice: "261.064F",
    },
    {
        id: 8,
        city: "Bobo-Dioulasso",
        country: "Burkina Faso",
        imageUrl: "/images/background/bg_2.jpg",
        flightOptions: [
            {
                dayOfWeek: "ven",
                date: "23 mai",
                departureAirport: "ABJ",
                arrivalAirport: "BOY",
                airline: "Air Burkina",
                isDirect: true,
            },
            {
                dayOfWeek: "ven",
                date: "30 mai",
                departureAirport: "BOY",
                arrivalAirport: "ABJ",
                airline: "Air Burkina",
                isDirect: true,
            },
        ],
        startingPrice: "271.684F",
    },
    {
        id: 9,
        city: "Cotonou",
        country: "Bénin",
        imageUrl: "/images/background/bg_3.jpg",
        flightOptions: [
            {
                dayOfWeek: "ven",
                date: "6 juin",
                departureAirport: "ABJ",
                arrivalAirport: "COO",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
            {
                dayOfWeek: "mar",
                date: "10 juin",
                departureAirport: "COO",
                arrivalAirport: "ABJ",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
        ],
        startingPrice: "272.216F",
    },
    {
        id: 10,
        city: "Casablanca",
        country: "Maroc",
        imageUrl: "/images/background/bg_4.jpg",
        flightOptions: [
            {
                dayOfWeek: "lun",
                date: "9 juin",
                departureAirport: "ABJ",
                arrivalAirport: "CMN",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
            {
                dayOfWeek: "dim",
                date: "15 juin",
                departureAirport: "CMN",
                arrivalAirport: "ABJ",
                airline: "Air Côte d'Ivoire",
                isDirect: true,
            },
        ],
        startingPrice: "280.743F",
    },
    {
        id: 11,
        city: "Le Caire",
        country: "Égypte",
        imageUrl: "/images/background/bg_5.jpg",
        flightOptions: [
            {
                dayOfWeek: "mer",
                date: "30 juil.",
                departureAirport: "ABJ",
                arrivalAirport: "CAI",
                airline: "EgyptAir",
                isDirect: true,
            },
            {
                dayOfWeek: "dim",
                date: "31 août",
                departureAirport: "CAI",
                arrivalAirport: "ABJ",
                airline: "EgyptAir",
                isDirect: true,
            },
        ],
        startingPrice: "367.671F",
    },
    {
        id: 12,
        city: "Douala",
        country: "Cameroun",
        imageUrl: "/images/background/bg_6.jpg",
        flightOptions: [
            {
                dayOfWeek: "ven",
                date: "20 juin",
                departureAirport: "ABJ",
                arrivalAirport: "DLA",
                airline: "Kenya Airways",
                isDirect: true,
            },
            {
                dayOfWeek: "lun",
                date: "23 juin",
                departureAirport: "DLA",
                arrivalAirport: "ABJ",
                airline: "Kenya Airways",
                isDirect: true,
            },
        ],
        startingPrice: "388.976F",
    },
]


export const carRentalOptions: CarRentalOption[] = [
    {
        id: 1,
        type: "Économique",
        description: "4-5 portes",
        imageUrl: "/images/background/car_1.png",
        passengers: 4,
        bags: 2,
        price: "38,485F",
    },
    {
        id: 2,
        type: "Compacte",
        description: "4-5 portes",
        imageUrl: "/images/background/car_2.png",
        passengers: 4,
        bags: 3,
        price: "61,772F",
    },
    {
        id: 3,
        type: "Intermédiaire",
        description: "Crossover",
        imageUrl: "/images/background/car_1.png",
        passengers: 5,
        bags: 4,
        price: "74,970F",
    },
    {
        id: 4,
        type: "Familiale",
        description: "SUV",
        imageUrl: "/images/background/car_2.png",
        passengers: 5,
        bags: 4,
        price: "104,599F",
    },
    {
        id: 5,
        type: "Premium",
        description: "Crossover",
        imageUrl: "/images/background/car_1.png",
        passengers: 5,
        bags: 2,
        price: "179,693F",
    }
]


export const locationOptions: LocationValue[] = [
  { code: "ABJ", name: "Abidjan", country: "Côte d'Ivoire", type: "airport" },
  { code: "NCE", name: "Nice", country: "France", type: "airport" },
  { code: "MRS", name: "Marseille", country: "France", type: "airport" },
  {
    code: "KR",
    name: "Corée du Sud",
    country: "Corée du Sud",
    type: "country",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    country: "Côte d'Ivoire",
    type: "country",
  },
  { code: "MJC", name: "Man", country: "Côte d'Ivoire", type: "airport" },
  { code: "DAD", name: "Đà Nẵng", country: "Vietnam", type: "airport" },
  { code: "TLN", name: "Toulon-Hyères", country: "France", type: "airport" },
  {
    code: "CXR",
    name: "Cam Ranh (Nha Trang)",
    country: "Vietnam",
    type: "airport",
  },
  { code: "HUI", name: "Huế", country: "Vietnam", type: "airport" },
  {
    code: "DOH",
    name: "Hamad International",
    country: "Qatar",
    type: "airport",
  },
  { code: "ISA", name: "Mont Isa", country: "Australie", type: "airport" },
];
